vars:
  - python: ./build/virtualenv/bin/python

stages:
    clean_data:
      cmd: ${python} src/process_data.py
      deps:
        - src/process_data.py
        - "./data/raw/SPAM text message 20170820 - Data.csv"
      outs:
        - ./data/processed/spam_data.csv
    train_test_split:
      cmd: ${python} src/train_test_split.py
      deps:
        - src/train_test_split.py
        - ./data/processed/spam_data.csv
      outs:
        - ./data/processed/train.csv
        - ./data/processed/test.csv
