vars:
  - python: ~/Documents/mantis/aimlac/deploying-machine-learning-models/build/virtualenv/bin/python

stages:
    clean_data:
      cmd: ${python} src/process_data.py
      deps:
        - src/process_data.py
        - "./data/raw/SPAM text message 20170820 - Data.csv"
      outs:
        - ./data/processed/spam_data.csv
    train_test_split:
      cmd: ${python} src/train_test_split.py
      params:
        - train_test_split
      deps:
        - src/train_test_split.py
        - ./data/processed/spam_data.csv
      outs:
        - ./data/processed/train.csv
        - ./data/processed/test.csv
    train:
      cmd: ${python} src/train.py
      params:
        - train
      deps:
        - src/train.py
        - ./data/processed/train.csv
        - ./data/processed/test.csv
      outs:
        - ./results/train_preds.csv
        - ./results/test_preds.csv
        - ./models/label_encoder.pk
        - ./models/model.pk
        - ./models/vectorizer.pk
    evaluate:
      foreach:
        - train
        - test
      do:
        cmd: >-
          ${python} src/evaluate.py
          --preds-path ./results/${item}_preds.csv
          --true-path ./data/processed/${item}.csv
          --label-encoder-path ./models/label_encoder.pk
          --metrics-path ./results/${item}_metrics.json
        deps:
          - src/evaluate.py
          - ./data/processed/train.csv
          - ./data/processed/test.csv
          - ./results/${item}_preds.csv
          - ./models/label_encoder.pk
        metrics:
          - ./results/${item}_metrics.json
